apiVersion: v1
kind: Service
metadata:
  name: employee-api
  namespace: employee-api
  labels:
    app: employee-api
spec:
  type: LoadBalancer
  selector:
    app: employee-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
